window.LUDUS_COPY = {
  pt: {
    brandTag: 'Experiências equestres privadas no Alqueva',
    navWho: 'Quem somos',
    navExperiences: 'Experiências',
    navGallery: 'Galeria',
    navLocation: 'Localização',
    navInfo: 'Informações importantes',
    ctaWhatsapp: 'WhatsApp',
    heroEyebrow: 'Passeios privados · Alqueva · Natureza',
    heroTitle: 'Experiências a cavalo privadas.',
    heroText: 'A Ludus Equus apresenta passeios e momentos equestres com acompanhamento próximo, ritmo tranquilo e contacto direto por WhatsApp.',
    heroPrimary: 'Falar no WhatsApp',
    heroSecondary: 'Ver experiências',
    whoEyebrow: 'Quem somos',
    whoTitle: 'Uma presença equestre moldada pela experiência e por um atendimento pessoal.',
    whoText1: 'A Ludus Equus cruza uma longa ligação ao mundo do cavalo com uma proposta serena e privada, pensada para o Alqueva.',
    whoText2: 'O tom é calmo, cuidado e direto, sem excesso de texto nem uma lógica de turismo massificado.',
    whoProof1Kicker: 'Experiência',
    whoProof1Value: '20+',
    whoProof1Text: 'anos ligados à atividade equestre, criação e cuidado com cavalos.',
    whoProof2Kicker: 'Formato',
    whoProof2Value: 'Privado',
    whoProof2Text: 'Passeios serenos, com acompanhamento próximo e sem lógica de massa.',
    whoProof3Kicker: 'Coordenação',
    whoProof3Value: 'WhatsApp',
    whoProof3Text: 'Reserva, detalhes e ponto de encontro tratados diretamente e sem ruído.',
    expEyebrow: 'Experiências',
    expTitle: 'Passeios a cavalo privados, com o Alqueva como cenário principal.',
    expText: 'As experiências são simples, reservadas e coordenadas diretamente por WhatsApp.',
    rideMainTitle: 'Passeios a cavalo no Alqueva',
    rideMainText: 'Ritmo calmo, paisagem aberta e uma experiência privada junto à água.',
    rideMainNote: 'Disponibilidade e detalhes são alinhados diretamente por WhatsApp.',
    rideFieldsTitle: 'Passeios nos campos',
    rideFieldsText: 'Percursos mais abertos, pensados para a paisagem, o silêncio e a ligação ao território.',
    rideFieldsNote: 'Coordenação sempre feita por WhatsApp.',
    rideCustomTitle: 'Experiências personalizadas',
    rideCustomText: 'Momentos à medida para pedidos especiais, com um formato mais íntimo e pessoal.',
    rideCustomNote: 'Cada pedido é alinhado individualmente por WhatsApp.',
    rideBookingNote: 'Disponibilidade e detalhes são alinhados diretamente por WhatsApp.',
    galleryEyebrow: 'Galeria',
    galleryTitle: 'Mais contexto visual para a paisagem, os cavalos e os momentos no terreno.',
    galleryText: 'A página pode crescer com mais imagens do arquivo, mantendo a leitura simples e muito apoiada na fotografia.',
    locationEyebrow: 'Localização',
    locationTitle: 'A experiência acontece no Alqueva, com ponto de encontro confirmado diretamente.',
    locationText1: 'A operação decorre na zona do Alqueva, num contexto de campo e barragem pensado para experiências privadas e ritmo tranquilo.',
    locationText2: 'O ponto de encontro exato, acessos e orientação final devem ser partilhados no momento da confirmação por WhatsApp.',
    locationButton: 'Ver zona no mapa',
    infoEyebrow: 'Informações importantes',
    infoTitle: 'Condições essenciais em seleção rápida.',
    infoText: 'Escolha um ponto para ver os detalhes, enquanto o rodapé mantém acesso à página com os termos completos.',
    term1Title: 'Contacto direto',
    term1Text: 'Disponibilidade, ponto de encontro e confirmação final devem ser tratados diretamente por WhatsApp.',
    term2Title: 'Formato privado',
    term2Text: 'A experiência é comunicada de forma reservada e personalizada, sem linguagem de operação massificada.',
    term3Title: 'Sem preços públicos',
    term3Text: 'O site apresenta o tipo de experiência, mas não publica valores na página pública.',
    term4Title: 'PT / EN',
    term4Text: 'A estrutura está preparada para português e inglês, mantendo a mesma leitura calma e objetiva.',
    contactEyebrow: 'Contacto',
    contactTitle: 'Para um primeiro contacto simples e pessoal, use o telefone, o email ou o WhatsApp.',
    contactText: 'Este é o ponto certo para esclarecer dúvidas, pedir disponibilidade e alinhar uma experiência privada de forma direta.',
    contactPhoneLabel: 'Telefone',
    contactEmailLabel: 'Email',
    contactButton: 'Abrir WhatsApp',
    footerText: 'Website informativo para experiências equestres privadas e momentos de campo no Alqueva.',
    fullTerms: 'Termos completos',
    termsBrandTag: 'Termos e responsabilidades completos',
    backHome: 'Voltar ao início',
    termsEyebrow: 'Informação importante',
    termsTitle: 'Termos e responsabilidades completos',
    termsIntro: 'Esta página reúne o texto legal completo, condições operacionais e regras detalhadas de participação. A homepage mantém apenas os cartões-resumo.',
    termsPoint1: 'Contacto direto para confirmar disponibilidade e ponto de encontro.',
    termsPoint2: 'Formato privado com acompanhamento pessoal e regras claras.',
    termsPoint3: 'Sem preços públicos: os valores são alinhados de forma direta.',
    legal1Title: 'Reservas e confirmação',
    legal1Text: 'Reservas, disponibilidade, ponto de encontro e confirmação final devem ser sempre validados diretamente com a operação.',
    legal2Title: 'Responsabilidades dos participantes',
    legal2Text: 'A participação depende do cumprimento das indicações dadas no local, das regras de segurança e das condições definidas para cada experiência.',
    legal3Title: 'Alterações operacionais',
    legal3Text: 'Condições meteorológicas, bem-estar animal, segurança ou questões logísticas podem exigir alterações de horário, percurso ou formato.',
    legal4Title: 'Cancelamentos e reembolsos',
    legal4Text: 'A política final de cancelamento, alteração de data e eventual reembolso deve ser confirmada com o texto legal aprovado pelo cliente.'
  },
  en: {
    brandTag: 'Private equestrian experiences in Alqueva',
    navWho: 'Who we are',
    navExperiences: 'Experiences',
    navGallery: 'Gallery',
    navLocation: 'Location',
    navInfo: 'Important info',
    ctaWhatsapp: 'WhatsApp',
    heroEyebrow: 'Private rides · Alqueva · Nature',
    heroTitle: 'Private, calm horse experiences.',
    heroText: 'Ludus Equus presents horse rides and equestrian moments with close guidance, a quieter pace, and direct WhatsApp contact.',
    heroPrimary: 'Talk on WhatsApp',
    heroSecondary: 'See experiences',
    whoEyebrow: 'Who we are',
    whoTitle: 'An equestrian presence shaped by experience and personal attention.',
    whoText1: 'Ludus Equus combines a long connection to the horse world with a calmer, more private proposal designed for Alqueva.',
    whoText2: 'The tone is careful, quiet, and direct, without excess text or a mass-tourism approach.',
    whoProof1Kicker: 'Experience',
    whoProof1Value: '20+',
    whoProof1Text: 'years connected to equestrian activity, breeding, and horse care.',
    whoProof2Kicker: 'Format',
    whoProof2Value: 'Private',
    whoProof2Text: 'Calm rides, close guidance, and no mass-tourism logic.',
    whoProof3Kicker: 'Coordination',
    whoProof3Value: 'WhatsApp',
    whoProof3Text: 'Booking, details, and meeting point handled directly and clearly.',
    expEyebrow: 'Experiences',
    expTitle: 'Private horse rides, with Alqueva as the main setting.',
    expText: 'The experiences are simple, reserved, and coordinated directly through WhatsApp.',
    rideMainTitle: 'Horse rides in Alqueva',
    rideMainText: 'A calm ride with open scenery and a private experience by the water.',
    rideMainNote: 'Availability and details are aligned directly through WhatsApp.',
    rideFieldsTitle: 'Rides in the fields',
    rideFieldsText: 'Open routes shaped by the landscape, the silence, and the connection to place.',
    rideFieldsNote: 'Coordination is always handled through WhatsApp.',
    rideCustomTitle: 'Personalized experiences',
    rideCustomText: 'Tailored moments for special requests, with a more intimate format.',
    rideCustomNote: 'Each request is aligned individually through WhatsApp.',
    rideBookingNote: 'Availability and details are aligned directly through WhatsApp.',
    galleryEyebrow: 'Gallery',
    galleryTitle: 'More visual context for the landscape, the horses, and the moments on site.',
    galleryText: 'The page can grow with more archive imagery while keeping the reading experience simple and strongly photography-led.',
    locationEyebrow: 'Location',
    locationTitle: 'The experience takes place in Alqueva, with the meeting point confirmed directly.',
    locationText1: 'The operation runs in the Alqueva area, in a countryside and waterside setting designed for private experiences and a calm pace.',
    locationText2: 'The exact meeting point, directions, and final guidance should be shared at confirmation time through WhatsApp.',
    locationButton: 'View area on map',
    infoEyebrow: 'Important info',
    infoTitle: 'Essential conditions in a quick selection.',
    infoText: 'Choose a point to see the details, while the footer keeps access to the full terms page.',
    term1Title: 'Direct contact',
    term1Text: 'Availability, meeting point, and final confirmation should be handled directly through WhatsApp.',
    term2Title: 'Private format',
    term2Text: 'The experience is communicated as reserved and personalized, without the language of a mass operation.',
    term3Title: 'No public pricing',
    term3Text: 'The site presents the type of experience, but does not publish prices on the public page.',
    term4Title: 'PT / EN',
    term4Text: 'The structure is prepared for Portuguese and English while keeping the same calm and objective reading experience.',
    contactEyebrow: 'Contact',
    contactTitle: 'For a simple and personal first contact, use phone, email, or WhatsApp.',
    contactText: 'This is the right place to ask questions, check availability, and align a private experience directly.',
    contactPhoneLabel: 'Phone',
    contactEmailLabel: 'Email',
    contactButton: 'Open WhatsApp',
    footerText: 'Informative website for private equestrian experiences and countryside moments in Alqueva.',
    fullTerms: 'Full terms',
    termsBrandTag: 'Full terms and responsibilities',
    backHome: 'Back to home',
    termsEyebrow: 'Important information',
    termsTitle: 'Full terms and responsibilities',
    termsIntro: 'This page gathers the full legal text, operating conditions, and detailed participation rules. The homepage keeps only the summary cards.',
    termsPoint1: 'Direct contact to confirm availability and the meeting point.',
    termsPoint2: 'Private format with personal guidance and clear rules.',
    termsPoint3: 'No public pricing: values are aligned directly.',
    legal1Title: 'Reservations and confirmation',
    legal1Text: 'Reservations, availability, meeting point, and final confirmation should always be validated directly with the operation.',
    legal2Title: 'Participant responsibilities',
    legal2Text: 'Participation depends on following the on-site instructions, the safety rules, and the conditions defined for each experience.',
    legal3Title: 'Operational changes',
    legal3Text: 'Weather conditions, animal welfare, safety, or logistical issues may require changes in schedule, route, or format.',
    legal4Title: 'Cancellations and refunds',
    legal4Text: 'The final cancellation, date-change, and refund policy should be confirmed with the legal text approved by the client.'
  }
};
