window.LUDUS_COPY = {
  pt: {
    brandTag: 'Experiências equestres privadas no Alqueva',
    navWho: 'Quem somos',
    navExperiences: 'Experiências',
    navGallery: 'Galeria',
    navLocation: 'Localização',
    navInfo: 'Informações importantes',
    ctaWhatsapp: 'WhatsApp',
    heroEyebrow: 'Passeios privados · Alqueva · Natureza',
    heroTitle: 'Experiências a cavalo privadas.',
    heroText: 'A Ludus Equus apresenta passeios e momentos equestres com acompanhamento próximo, ritmo tranquilo e contacto direto por WhatsApp.',
    heroPrimary: 'Falar no WhatsApp',
    heroSecondary: 'Ver experiências',
    whoEyebrow: 'Quem somos',
    whoTitle: 'Uma presença equestre moldada pela experiência, pelo território e por um atendimento pessoal.',
    whoText1: 'A Ludus Equus cruza uma longa ligação ao mundo do cavalo com uma proposta mais serena e privada, pensada para o Alqueva.',
    whoText2: 'O tom é calmo, cuidado e direto. O site apresenta a essência do projeto sem excesso de texto nem uma lógica de turismo massificado.',
    statsKicker: 'Experiência',
    statsText: 'anos ligados à atividade equestre, criação e cuidado com cavalos.',
    expEyebrow: 'Experiências',
    expTitle: 'Uma apresentação simples, visual e sem preços públicos.',
    expText: 'A página mostra apenas o essencial: tipos de experiência, posicionamento e convite ao contacto direto para cada pedido.',
    card1Title: 'Passeios a cavalo',
    card1Text: 'Percursos privados pensados para a paisagem, o ritmo e uma relação mais tranquila com o território.',
    card2Title: 'Universo equestre',
    card2Text: 'Uma forma de apresentar o percurso da marca, a experiência com cavalos e a identidade equestre do projeto.',
    card3Title: 'Momentos no campo',
    card3Text: 'Experiências rurais e lúdicas com comunicação contida, foco visual e coordenação personalizada.',
    galleryEyebrow: 'Galeria',
    galleryTitle: 'Mais contexto visual para a paisagem, os cavalos e os momentos no terreno.',
    galleryText: 'A página pode crescer com mais imagens do arquivo, mantendo a leitura simples e muito apoiada na fotografia.',
    locationEyebrow: 'Localização',
    locationTitle: 'A experiência acontece no Alqueva, com ponto de encontro confirmado diretamente.',
    locationText1: 'A operação decorre na zona do Alqueva, num contexto de campo e barragem pensado para experiências privadas e ritmo tranquilo.',
    locationText2: 'O ponto de encontro exato, acessos e orientação final devem ser partilhados no momento da confirmação por WhatsApp.',
    locationButton: 'Ver zona no mapa',
    infoEyebrow: 'Informações importantes',
    infoTitle: 'Condições essenciais resumidas em cartões curtos.',
    infoText: 'Os pontos principais ficam aqui para leitura rápida, enquanto o rodapé mantém acesso à página com os termos completos.',
    term1Title: 'Contacto direto',
    term1Text: 'Disponibilidade, ponto de encontro e confirmação final devem ser tratados diretamente por WhatsApp.',
    term2Title: 'Formato privado',
    term2Text: 'A experiência é comunicada de forma reservada e personalizada, sem linguagem de operação massificada.',
    term3Title: 'Sem preços públicos',
    term3Text: 'O site apresenta o tipo de experiência, mas não publica valores na página pública.',
    term4Title: 'PT / EN',
    term4Text: 'A estrutura está preparada para português e inglês, mantendo a mesma leitura calma e objetiva.',
    contactEyebrow: 'Contacto',
    contactTitle: 'Para um primeiro contacto simples e pessoal, o WhatsApp é o canal principal.',
    contactText: 'Este é o ponto certo para esclarecer dúvidas, pedir disponibilidade e alinhar uma experiência privada de forma direta.',
    contactButton: 'Abrir WhatsApp',
    footerText: 'Website informativo para experiências equestres privadas e momentos de campo no Alqueva.',
    fullTerms: 'Termos completos',
    termsBrandTag: 'Termos e responsabilidades completos',
    backHome: 'Voltar ao início',
    termsEyebrow: 'Informação importante',
    termsTitle: 'Termos e responsabilidades completos',
    termsIntro: 'Esta página reúne o texto legal completo, condições operacionais e regras detalhadas de participação. A homepage mantém apenas os cartões-resumo.',
    legal1Title: 'Reservas e confirmação',
    legal1Text: 'Reservas, disponibilidade, ponto de encontro e confirmação final devem ser sempre validados diretamente com a operação.',
    legal2Title: 'Responsabilidades dos participantes',
    legal2Text: 'A participação depende do cumprimento das indicações dadas no local, das regras de segurança e das condições definidas para cada experiência.',
    legal3Title: 'Alterações operacionais',
    legal3Text: 'Condições meteorológicas, bem-estar animal, segurança ou questões logísticas podem exigir alterações de horário, percurso ou formato.',
    legal4Title: 'Cancelamentos e reembolsos',
    legal4Text: 'A política final de cancelamento, alteração de data e eventual reembolso deve ser confirmada com o texto legal aprovado pelo cliente.'
  },
  en: {
    brandTag: 'Private equestrian experiences in Alqueva',
    navWho: 'Who we are',
    navExperiences: 'Experiences',
    navGallery: 'Gallery',
    navLocation: 'Location',
    navInfo: 'Important info',
    ctaWhatsapp: 'WhatsApp',
    heroEyebrow: 'Private rides · Alqueva · Nature',
    heroTitle: 'Private, calm horse experiences shaped by the Alqueva landscape.',
    heroText: 'Ludus Equus presents horse rides and equestrian moments with close guidance, a quieter pace, and direct WhatsApp contact.',
    heroPrimary: 'Talk on WhatsApp',
    heroSecondary: 'See experiences',
    whoEyebrow: 'Who we are',
    whoTitle: 'An equestrian presence shaped by experience, place, and personal attention.',
    whoText1: 'Ludus Equus combines a long connection to the horse world with a calmer, more private proposal designed for Alqueva.',
    whoText2: 'The tone is careful, quiet, and direct. The site presents the essence of the project without excess text or a mass-tourism approach.',
    statsKicker: 'Experience',
    statsText: 'years connected to equestrian activity, breeding, and horse care.',
    expEyebrow: 'Experiences',
    expTitle: 'A simple, visual presentation with no public pricing.',
    expText: 'The page shows only the essentials: experience types, positioning, and an invitation to direct contact for each request.',
    card1Title: 'Horse rides',
    card1Text: 'Private routes designed around the landscape, the pace, and a calmer relationship with the territory.',
    card2Title: 'Equestrian background',
    card2Text: 'A way to present the brand journey, its horse experience, and the project’s equestrian identity.',
    card3Title: 'Countryside moments',
    card3Text: 'Rural and leisure experiences with restrained communication, visual focus, and personalized coordination.',
    galleryEyebrow: 'Gallery',
    galleryTitle: 'More visual context for the landscape, the horses, and the moments on site.',
    galleryText: 'The page can grow with more archive imagery while keeping the reading experience simple and strongly photography-led.',
    locationEyebrow: 'Location',
    locationTitle: 'The experience takes place in Alqueva, with the meeting point confirmed directly.',
    locationText1: 'The operation runs in the Alqueva area, in a countryside and waterside setting designed for private experiences and a calm pace.',
    locationText2: 'The exact meeting point, directions, and final guidance should be shared at confirmation time through WhatsApp.',
    locationButton: 'View area on map',
    infoEyebrow: 'Important info',
    infoTitle: 'Essential conditions summarized in short cards.',
    infoText: 'The main points stay here for quick reading, while the footer keeps access to the full terms page.',
    term1Title: 'Direct contact',
    term1Text: 'Availability, meeting point, and final confirmation should be handled directly through WhatsApp.',
    term2Title: 'Private format',
    term2Text: 'The experience is communicated as reserved and personalized, without the language of a mass operation.',
    term3Title: 'No public pricing',
    term3Text: 'The site presents the type of experience, but does not publish prices on the public page.',
    term4Title: 'PT / EN',
    term4Text: 'The structure is prepared for Portuguese and English while keeping the same calm and objective reading experience.',
    contactEyebrow: 'Contact',
    contactTitle: 'For a simple and personal first contact, WhatsApp is the main channel.',
    contactText: 'This is the right place to ask questions, check availability, and align a private experience directly.',
    contactButton: 'Open WhatsApp',
    footerText: 'Informative website for private equestrian experiences and countryside moments in Alqueva.',
    fullTerms: 'Full terms',
    termsBrandTag: 'Full terms and responsibilities',
    backHome: 'Back to home',
    termsEyebrow: 'Important information',
    termsTitle: 'Full terms and responsibilities',
    termsIntro: 'This page gathers the full legal text, operating conditions, and detailed participation rules. The homepage keeps only the summary cards.',
    legal1Title: 'Reservations and confirmation',
    legal1Text: 'Reservations, availability, meeting point, and final confirmation should always be validated directly with the operation.',
    legal2Title: 'Participant responsibilities',
    legal2Text: 'Participation depends on following the on-site instructions, the safety rules, and the conditions defined for each experience.',
    legal3Title: 'Operational changes',
    legal3Text: 'Weather conditions, animal welfare, safety, or logistical issues may require changes in schedule, route, or format.',
    legal4Title: 'Cancellations and refunds',
    legal4Text: 'The final cancellation, date-change, and refund policy should be confirmed with the legal text approved by the client.'
  }
};
